Replace the rest of the modal components
Automattic/woocommerce-services pull request #2340
Opened 2021-02-25 05:24 UTC by c-shultz

## Description

### Related issue(s)

### Steps to reproduce & screenshots/GIFs

### Checklist

- [ ] unit tests

- [ ] `changelog.txt` entry added

2021-03-05 15:06 UTC, waclawjacek requested changes
Nice! 👍 

I noticed some issues and left some suggestions. I am not sure if all of the design-related ones should be addressed at this stage.

2021-03-05 21:47 UTC, c-shultz commented on client/components/button-modal/index.js
> +				{ buttons && buttons.map( ( b, index ) => buildButton( b, index ) ) }
Oh nice. That's a good cleanup

2021-03-05 21:49 UTC, c-shultz commented on client/extensions/woocommerce/woocommerce-services/views/carrier-accounts/list-item.js
>  				<div className="carrier-accounts__settings-cancel-dialog-header">
Thanks for catching this one. 💯 I must have missed the testing on this.

2021-03-05 21:51 UTC, c-shultz commented on client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/packages-step/add-item.js
>  			buttons={ buttons }
I think we're probably good to remove the separate and use the more native styling of the component, but I'll at least get some more space between the content and the buttons

2021-03-05 23:25 UTC, c-shultz commented on client/extensions/woocommerce/woocommerce-services/views/carrier-accounts/ups-settings-form.js
> +		</ButtonModal>
Here's where I landed on this one 
<img width="478" alt="image" src="https://user-images.githubusercontent.com/6209518/110185364-032a4d80-7dc7-11eb-84e6-81c212131981.png">

2021-03-15 19:49 UTC, c-shultz commented
There's some good issues here found by @waclawjacek. I need to rework some style conflicts which has increased the scope a good amount. I'm going to pause on this, leave the branch, and plan on returning to this once our team is focusing on shipping again.

2025-04-16 16:29 UTC, samnajian commented
I'm retiring the super old draft.

2025-04-16 16:29 UTC, closed without merging