Move Calypso's FormButton out into our own component folder
Automattic/woocommerce-services pull request #2443
Opened 2021-07-01 18:25 UTC by harriswong

## Description
Similar to https://github.com/Automattic/woocommerce-services/pull/2344, There is no comparable WordPress nor WooCommerce `FormButton`. I moved the Calypso submodule's `FormButton` over.

### Related issue(s)
https://github.com/Automattic/woocommerce-services/issues/2333

### Steps to reproduce & screenshots/GIFs
1. Pull this branch, run `npm run start` to recompile the assets
2.  Go to an order, click "Create new label" 
3. Make sure the "Verify address" button works. 

### Checklist

- [ ] unit tests

- [ ] `changelog.txt` entry added

2021-07-01 23:40 UTC, harriswong commented
I'm looking into updating `import Button from 'components/button';` to `import { Button } from '@wordpress/components';` Moving this back to "in progress".

2021-07-02 23:40 UTC, harriswong commented on client/components/forms/form-button/index.js
> +				'is-borderless': !! this.props.borderless
Added handling for `borderless` prop that we use in a few cases. Using `is-borderless` similar to https://github.com/Automattic/woocommerce-services/pull/2361/files#diff-dc83733ab281e3cf1cb35835dbedfc2abdd540bf59d78e0f4e4e55863c3edab4R229.

2021-07-02 23:41 UTC, harriswong commented on client/components/forms/form-button/style.scss
> +		margin-left: 0;
Added this CSS to remove margin for first button if they are side by side.

2023-02-17 20:04 UTC, waclawjacek commented
LGTM! Except for this tiny quirk when reloading the WCS&T settings page:

https://user-images.githubusercontent.com/1759681/219782061-ed4d0835-5615-425b-9685-535b274d8ae3.mp4

2023-02-17 20:06 UTC, waclawjacek requested changes
LGTM except for a tiny thing mentioned above.

2023-02-23 18:00 UTC, harriswong commented
While looking into the CSS issue with the button, I concluded that we don't need a clickable button for placeholders. Reasons are as follow:

1. During rendering, users shouldn't be allowed to click on "Save settings"
2. For the purpose of rendering placeholders, we don't really need to show the button.

I have removed it
![image](https://user-images.githubusercontent.com/572862/220991257-35309124-db4b-4e1d-bc2a-417f492ce617.png)

2023-02-24 12:21 UTC, waclawjacek approved these changes
:shipit: :shipit: :shipit:

2023-02-25 00:53 UTC, merged