Fix/issue 2511
Automattic/woocommerce-services pull request #2512
Opened 2021-12-06 08:18 UTC by dustinparker

## Description

We needed to add logic to ensure the connect server only validates the address name field if using a version of WCS newer than 1.25.20.
### Related issue(s)

Fixes #2511 

### Steps to reproduce & screenshots/GIFs

1. Make sure you are using WCC branch fix/wcs-issue-2511 and that [this constant](https://github.com/Automattic/woocommerce-services/blob/a0b068d3124dc661c48cbdaf29e0f2f7ad8fc125/woocommerce-services.php#L48) is set to 5.
2. Create an order and create a label for that order.
3. Add a blank space to the origin/destination name field and click verify address.
4. The address should be verified automatically if the address is valid.
5. Change [this constant](https://github.com/Automattic/woocommerce-services/blob/a0b068d3124dc661c48cbdaf29e0f2f7ad8fc125/woocommerce-services.php#L48) to 6.
6. Change WCS to version 1.25.21 (I just hardcoded the passed version [here](https://github.com/Automattic/woocommerce-connect-server/blob/8e5aebed5932f8d09aa6a1dadc276690a066b620/lib/shipping/handler.js#L198))
7. Now try to create a shipping label for the order.
8. Add a blank space to the origin/destination name field and click verify address.
9. An error should be returned.
10. Add a name to the origin/destination name field and click verify address.
11. The address should be verified automatically if the address is valid.

### Checklist

- [ ] unit tests

- [x] `changelog.txt` entry added

2021-12-09 11:43 UTC, iyut approved these changes
I have tested this code as in description. It works separating the checks for WCC server api version 5 and 6. LGTM!

2021-12-10 21:32 UTC, waclawjacek requested changes
I'm adding suggestions for removing the API version checks as per our chat. I'm fairly certain they aren't necessary but please verify that before including these changes.

2021-12-10 21:32 UTC, waclawjacek commented on classes/class-wc-rest-connect-address-normalization-controller.php
> +		}
I'm fairly certain these version checks aren't necessary, as per our chat.

```suggestion
		$name = $address['name'];
		unset( $address['name'] );
```

2021-12-10 21:32 UTC, waclawjacek commented on classes/class-wc-rest-connect-address-normalization-controller.php
> +		}
```suggestion
		$response->normalized->name = $name;
```

2021-12-14 15:21 UTC, closed without merging