Change API version back to 5.
Automattic/woocommerce-services pull request #2515
Opened 2021-12-14 21:17 UTC by dustinparker

## Description

We needed to add logic to ensure the connect server only validates the address name field if using a version of WCS newer than 1.25.20.
### Related issue(s)

Fixes #2511 

### Steps to reproduce & screenshots/GIFs

1. Make sure you are using WCC branch fix/wcs-issue-2511.
2. Change WCS to version 1.25.21 (I just hardcoded the passed version [here](https://github.com/Automattic/woocommerce-connect-server/blob/8e5aebed5932f8d09aa6a1dadc276690a066b620/lib/shipping/handler.js#L198))
3. Now try to create a shipping label for the order.
4. Add a blank space to the origin/destination name field and click verify address.
5. An error should be returned.
6. Add a name to the origin/destination name field and click verify address.
7. The address should be verified automatically if the address is valid.

### Checklist

- [ ] unit tests

- [x] `changelog.txt` entry added

2021-12-15 06:47 UTC, iyut commented
Hi @dustinparker , 

I have tried to test this. It does block the user when the name field in destination address is empty. But I'm not sure if the error that I get is the correct one. 

Here is what I did : 
1. change the WCS version in woocommerce-services.php : ` * Version: 1.25.21`
2. change the version in package.json file : 
```
{
  "name": "woocommerce-services",
  "version": "1.25.21",
...
...
}
```
3. Create an order.
4. Try to create shipping label.
5. let the name field empty by using [space].
6. This is the error that I get : 
![screenshot-localhost_8050-2021 12 15-13_45_19](https://user-images.githubusercontent.com/631098/146136994-e9f28831-5f79-4a09-9925-5cb88927128c.png)

I'm not sure whether this is the correct error message that I should get or not. If it's the correct error, then I will approve this PR.

2021-12-15 11:56 UTC, waclawjacek requested changes
Unfortunately something isn't working on my end. It looks to be related to this commit that was introduced on `trunk` a while back: 01c3f2ea7d0800ec2f4388e353755aa69a5e7ab1

This is the error I get when providing a non-empty name:
![Markup on 2021-12-15 at 12:49:35](https://user-images.githubusercontent.com/1759681/146182301-3883df2f-5aa7-4b09-a834-85d774c51cab.png)
![Markup on 2021-12-15 at 12:50:14](https://user-images.githubusercontent.com/1759681/146182312-955025e7-6fb4-4751-9489-de59bbbdc200.png)

An unit test should catch this. 🤔 Could you please add one that will test this and a valid case?

2021-12-15 11:56 UTC, waclawjacek commented on woocommerce-services.php
>  	if ( ! defined( 'WOOCOMMERCE_CONNECT_SERVER_API_VERSION ' ) ) {
This is entirely unrelated to your PR but it looks like a trailing space snuck into this line. Could you please remove it?

```suggestion
	if ( ! defined( 'WOOCOMMERCE_CONNECT_SERVER_API_VERSION' ) ) {
```

2021-12-15 11:56 UTC, waclawjacek commented on changelog.txt
> +* Fix - Change WOOCOMMERCE_CONNECT_SERVER_API_VERSION back to 5.
The const is [still set to `5` in the previously released `1.25.20`](https://github.com/Automattic/woocommerce-services/blob/1.25.20/woocommerce-services.php#L48) so from a release-to-release standpoint, nothing's changed. Let's remove this entry.

```suggestion
```

2022-01-05 10:22 UTC, dustinparker commented
> Unfortunately something isn't working on my end. It looks to be related to this commit that was introduced on `trunk` a while back: [01c3f2e](https://github.com/Automattic/woocommerce-services/commit/01c3f2ea7d0800ec2f4388e353755aa69a5e7ab1)
> 
> This is the error I get when providing a non-empty name: ![Markup on 2021-12-15 at 12:49:35](https://user-images.githubusercontent.com/1759681/146182301-3883df2f-5aa7-4b09-a834-85d774c51cab.png) ![Markup on 2021-12-15 at 12:50:14](https://user-images.githubusercontent.com/1759681/146182312-955025e7-6fb4-4751-9489-de59bbbdc200.png)
> 
> An unit test should catch this. thinking Could you please add one that will test this and a valid case?

hey @waclawjacek, if we release the Connect Server change that adds name to the Joi schema, this will actually no longer be an issue. We'd just need to make sure the WCC change is released before this WCS change. It seems like a unit test wouldn't be necessary in that case. Let me know what you think. Thanks!

2022-01-06 09:09 UTC, waclawjacek approved these changes
> We'd just need to make sure the WCC change is released before this WCS change.

Ah, I see! Thanks! LGTM! :shipit: 

Could you put a note in the Fulfill Extension Releases spreadsheet that the Connect Server should be deployed before deploying the WCS&T extension?

2022-01-18 12:57 UTC, merged