Fix/issue 2249 - Add filter around TaxJar class to give a user an option to override TaxJar result
Automattic/woocommerce-services pull request #2561
Opened 2022-06-14 10:53 UTC by iyut

## Description
The current TaxJar class doesnt have a way for the user to override TaxJar result. This PR add a couple of filter that the user can use to override the TaxJar result.

### Related issue(s)

Closes #2249 

### Steps to reproduce & screenshots/GIFs
1. Add this snippet in your `theme/functions.php` file : 
```
function change_taxjar_tax( $tax_value, $taxes, $body ) {
	if ( 'DE-BE' === $body['to_state'] && '10115' === $body['to_zip'] ) {
		$tax_value = 0.19;
	}
	return $tax_value;
}

add_filter( 'woocommerce_services_override_tax_rate', 'change_taxjar_tax', 10, 3 );
```
2. Enable `Automatic Tax Rate` from **WooCommerce >> Settings >> Tax**.
3. Add any product to the cart and checkout with this shipping address :
`Berlin, Germany, 10178`.
4. Check the tax rate in the cart. It will always be 19%. 

### Checklist

- [ ] unit tests

- [x] `changelog.txt` entry added

2022-06-30 10:06 UTC, bartech requested changes

2022-06-30 10:06 UTC, bartech commented on classes/class-wc-connect-taxjar-integration.php
> +		$skip_taxjar_request_taxes = apply_filters( 'woocommerce_services_skip_taxjar_request', false, $taxes, $body );
No need to send `$taxes` in this filter, at this point `$taxes` will always be array with placeholder values.

2022-06-30 10:06 UTC, bartech commented on classes/class-wc-connect-taxjar-integration.php
> +			return apply_filters( 'woocommerce_services_taxjar_calculate_tax_result', $skip_taxjar_request_taxes, null, $body, true );
Suggest to rename this filter to `woocommerce_services_custom_tax_result` pass `$taxes` as first parammeter to convey what shape returned value should be. Think using same filter name in different places will be more confusing. It will require developer to exemine values passed by filter to know in which place same filter was triggered.
```suggestion
return apply_filters( 'woocommerce_services_custom_tax_result', $taxes, $body );
```

2022-07-06 07:15 UTC, iyut commented
@bartech , I have made some changes for this PR and the description on how to test it. Could you try to pull and have a test again? And also let me know what you think.

2022-07-07 08:13 UTC, bartech requested changes

2022-07-07 08:13 UTC, bartech commented on classes/class-wc-connect-taxjar-integration.php
> +		$custom_response = apply_filters( 'woocommerce_services_custom_response', array(), $taxes, $body );
Suggest to remove this filter also this PR. Let's move it to another PR. Will be good to use similar approach as with `maybe_override_taxjar_tax`

2022-07-07 08:13 UTC, bartech commented on classes/class-wc-connect-taxjar-integration.php
> +	public function override_taxjar_tax( $taxjar_resp_tax, $body ) {
Let's rename this method to `maybe_override_taxjar_tax`

2022-07-07 08:13 UTC, bartech commented on classes/class-wc-connect-taxjar-integration.php
> +		if ( $new_tax_rate !== $taxjar_resp_tax->rate ) {
Let's revert condition check and do early return if `$new_tax_rate === $taxjar_resp_tax->rate` before comparing let's cast each value to float by using `floatval`

2022-07-12 08:06 UTC, bartech approved these changes

2022-07-13 04:14 UTC, merged