fix: warning on checkout page
Automattic/woocommerce-services pull request #2612
Opened 2022-11-29 15:49 UTC by Splagov

- fixed issue when warning on checkout page apper if zipcode doesn't match selected state.

## Description

### Related issue(s)

### Steps to reproduce & screenshots/GIFs

### Checklist

- [ ] unit tests

- [ ] `changelog.txt` entry added

2022-11-29 18:35 UTC, bartech requested changes
I run the code on my local and looks good. 
Please only address code formatting.

2022-11-29 18:35 UTC, bartech commented on classes/class-wc-connect-taxjar-integration.php
> +		if( ! isset($taxjar_resp_tax) ) return;
WordPress Coding standards: Inline control structures are not allowed.
```suggestion
		if ( ! isset( $taxjar_resp_tax ) ) {
			return;
		}
```

2022-12-01 09:16 UTC, bartech approved these changes

2022-12-02 07:49 UTC, Splagov commented
how I can run JS Eslint and Test and PHP Syntax Check  ?

2022-12-22 09:37 UTC, bartech approved these changes

2023-01-20 12:58 UTC, merged

2023-01-24 18:46 UTC, harriswong commented
Added missing changelog and readme entry in this commit: https://github.com/Automattic/woocommerce-services/commit/087b5831d9d9532cb31e456869536ce61ab96655