Fix failing PHP tests
Automattic/woocommerce-services pull request #2663
Opened 2023-07-04 11:22 UTC by samnajian

## Description
Our test suit had issues running MariaDB with `mariadb:latest` and this PR pins the version number to the latest working version.

2023-07-04 17:49 UTC, waclawjacek requested changes
What a great solution! Suggesting what I think is an improvement (adding some escaping).

2023-07-04 17:49 UTC, waclawjacek commented on .github/workflows/php_tests.yml
> +        run: echo "WC_PNPM=$(node -p "require('/tmp/woocommerce/plugins/woocommerce/package.json').engines.pnpm")"  >> $GITHUB_OUTPUT
This works but I think the quotes should be escaped. What's happening right now is this (string concatenation):

```
waclaw@Waclaws-MacBook-Pro woocommerce % echo "hey"foo"hey"
heyfoohey
```

How about this instead?

```suggestion
        run: echo "WC_PNPM=$(node -p \"require('/tmp/woocommerce/plugins/woocommerce/package.json').engines.pnpm\")" >> "$GITHUB_OUTPUT"
```

2023-07-04 18:50 UTC, samnajian commented
@waclawjacek The applied suggestion didn't work, not sure what I should do with it, would it be fine to revert the last commit?

2023-07-04 19:08 UTC, waclawjacek requested changes

2023-07-04 19:08 UTC, waclawjacek commented on .github/workflows/php_tests.yml
> +        run: echo "WC_PNPM=$(node -p \"require('/tmp/woocommerce/plugins/woocommerce/package.json').engines.pnpm\")" >> "$GITHUB_OUTPUT"
Sorry, my bad! I've just learned that using `$()` creates a new quoting context. So this should work (it does when I test it locally after defining `GITHUB_OUTPUT`):

```suggestion
        run: echo "WC_PNPM=$(node -p "require('/tmp/woocommerce/plugins/woocommerce/package.json').engines.pnpm")" >> "$GITHUB_OUTPUT"
```

2023-07-05 09:04 UTC, waclawjacek approved these changes

2023-07-05 09:06 UTC, merged