Add a "deactivated" message to the plugins list entry
Automattic/woocommerce-services pull request #2759
Opened 2024-06-26 15:21 UTC by Ferdev

-------

## Description
Displays a message in the plugin's plugins list entry, letting the user know that the plugin was deactivated and the data transfered successfully after the migration process.

### Related issue(s)

N/A

### Steps to reproduce & screenshots/GIFs

1. Remove the `false` statement in line 1538 of `woocommerce-services.php`.
2. Visit the plugins list.
3. The message should be displayed below the WooCommerce Tax row.

### Checklist

- [ ] unit tests

- [ ] `changelog.txt` entry added
- [ ] `readme.txt` entry added

2024-06-26 15:34 UTC, kloon requested changes
Banner shows, just some changes needed to the escaping and text domain, then good to go.

2024-06-26 15:34 UTC, kloon commented on woocommerce-services.php
> +						__( 'WooCommerce Shipping & Tax has been deactivated. Your data and settings have been carried over to the dedicated WooCommerce Shipping and WooCommerce Tax extensions.<br />For support, pleas
```suggestion
						__( 'WooCommerce Shipping & Tax has been deactivated. Your data and settings have been carried over to the dedicated WooCommerce Shipping and WooCommerce Tax extensions.<br />For support, please <a href="https://woocommerce.com/my-account/create-a-ticket/">contact our Happiness Engineers</a>.', 'woocommerce-services' )
```

2024-06-26 15:34 UTC, kloon commented on woocommerce-services.php
> +				esc_html(
When doing an sprintf I believe one should escape on the variable side. PHPCS complains about the variable side not being escaped.

2024-06-28 10:39 UTC, kloon approved these changes
Latest changes looks good. Thanks @Ferdev!

I assume we will be hooking up the logic in a different PR to ensure when to show the notice?

2024-06-28 16:19 UTC, Ferdev commented
Awesome, thanks @kloon !

> I assume we will be hooking up the logic in a different PR to ensure when to show the notice?

Yeah, I created a [follow up](https://github.com/woocommerce/shipping/issues/144) for that the other day.

2024-06-28 16:19 UTC, merged