Tweak/issue 2822 - WordPress 6.7 Compatibility
Automattic/woocommerce-services pull request #2823
Opened 2024-10-16 15:06 UTC by iyut

### Description
Testing the plugin on WordPress 6.7 Beta to make sure its compatibility. Then bump the `Tested up to` version.

### Testing Instructions

1. Install [WordPress Beta Tester](https://wordpress.org/plugins/wordpress-beta-tester/) plugin.
2. Select the “Bleeding edge” channel and “Beta/RC Only” stream.
3. Test the plugin using WP 6.7 beta version.
4. Make sure no error listed in log file.

### Related issue(s)
Fixes #2822 

### Checklist

- [ ] unit tests

- [x] `changelog.txt` entry added
- [x] `readme.txt` entry added

2024-10-17 08:49 UTC, Abdalsalaam approved these changes
I tested it and all looks good

2024-10-18 06:49 UTC, dustinparker requested changes
Everything appears to work correctly. The same warning is showing up on this plugin:

>Function load_plugin_textdomain was called incorrectly. Attempted to load translations for the woocommerce-services domain too early. Translations should be loaded after the after_setup_theme action has fired, to ensure that the current user is already set up. (This message was added in version 6.7.0.)

2024-10-24 09:58 UTC, kloon commented
Hey @iyut, to fix the failing test, you can have a look at what @samnajian did in [this WC Shipping PR](https://github.com/woocommerce/woocommerce-shipping/pull/866)

2024-10-24 11:49 UTC, iyut commented
Thanks @kloon @samnajian , following the PR does fix the issue!

2024-10-25 07:59 UTC, dustinparker approved these changes
Everything works as expected and no WP 6.7 errors. LGTM!

2024-10-28 04:08 UTC, merged